language: python
python:
  - "3.5"
  - "3.6"
  - "3.7-dev"

services:
  - postgresql

before_script:
  - psql --command "CREATE DATABASE meowder;"
  - psql --command "CREATE USER johnsmith WITH PASSWORD 'johnsmithspassword';"
  - psql --command "ALTER ROLE johnsmith SET client_encoding TO 'utf8';"
  - psql --command "ALTER ROLE johnsmith SET default_transaction_isolation TO 'read committed';"
  - psql --command "ALTER ROLE johnsmith SET timezone TO 'UTC';"
  - psql --command "GRANT ALL PRIVILEGES ON DATABASE meowder TO johnsmith;"

script:
  - cp .env.example .env
  - ./manage.py check
  - ./manage.py migrate
  - ./manage.py seed_database large
