sudo: required

services:
  - docker

before_script:
  - docker pull mwiens91/meowder-test-build

script:
  - docker run -d --name meowder-container mwiens91/meowder-test-build sleep infinity
  - docker exec meowder-container meowder/manage.py check
