sudo: required

services:
  - docker

before_script:
  - docker pull mwiens91/meowder-test-build

script:
  - docker container create --name meowder-container mwiens91/meowder-test-build
  - docker run meowder-container "/meowder/manage.py check"
