# Generated by Django 2.0.1 on 2018-01-06 02:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breed', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('sex', models.CharField(choices=[('F', 'F'), ('M', 'M'), ('X', 'X')], default='F', max_length=1)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(choices=[(1, 1), (-1, -1)], default=1)),
                ('votee', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='votee', to='cats.Cat')),
                ('voter', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='voter', to='cats.Cat')),
            ],
        ),
        migrations.AddField(
            model_name='cat',
            name='votes',
            field=models.ManyToManyField(through='cats.Vote', to='cats.Cat'),
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('voter', 'votee')},
        ),
    ]
