# Generated by Django 2.0.1 on 2018-01-09 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0002_profile_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
    ]
