# Generated by Django 2.0.1 on 2018-01-09 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0004_auto_20180109_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='profilepic',
            field=models.URLField(blank=True, null=True),
        ),
    ]
