# Generated by Django 2.0.1 on 2018-01-09 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0005_cat_profilepic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='profilepic',
            field=models.URLField(blank=True, default='/static/default_profile_pic.png', null=True),
        ),
    ]
