# Generated by Django 2.0.1 on 2018-01-10 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0006_auto_20180109_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='pic1',
            field=models.URLField(blank=True, null=True, verbose_name='picture 1'),
        ),
        migrations.AddField(
            model_name='cat',
            name='pic2',
            field=models.URLField(blank=True, null=True, verbose_name='picture 2'),
        ),
        migrations.AddField(
            model_name='cat',
            name='pic3',
            field=models.URLField(blank=True, null=True, verbose_name='picture 3'),
        ),
        migrations.AlterField(
            model_name='cat',
            name='profilepic',
            field=models.URLField(blank=True, default='http://www.emoji.co.uk/files/google-emojis/animals-nature-android/7465-cat.png', null=True, verbose_name='profile picture'),
        ),
    ]
