# Generated by Django 2.0.1 on 2018-01-12 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0008_auto_20180110_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='pic1',
            field=models.URLField(help_text='One picture required', null=True, verbose_name='picture 1'),
        ),
        migrations.AlterField(
            model_name='cat',
            name='profilepic',
            field=models.URLField(blank=True, default='http://www.emoji.co.uk/files/google-emojis/animals-nature-android/7465-cat.png', help_text='This will be scaled to 250x250px', null=True, verbose_name='profile picture'),
        ),
    ]
