# Generated by Django 2.0.1 on 2018-02-05 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0009_auto_20180112_2038'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateField()),
                ('dismissed', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='cat',
            name='profilepic',
            field=models.URLField(blank=True, help_text='Optional. This will be scaled to 250x250px', null=True, verbose_name='profile picture'),
        ),
        migrations.AddField(
            model_name='match',
            name='othercat',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='matchedcat', to='cats.Cat'),
        ),
        migrations.AddField(
            model_name='match',
            name='thiscat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matchingcat', to='cats.Cat'),
        ),
    ]
