# Generated by Django 2.0.1 on 2018-02-05 22:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0010_auto_20180205_2133'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='othercat',
            new_name='matchedcat',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='thiscat',
            new_name='matchingcat',
        ),
        migrations.AlterField(
            model_name='match',
            name='time',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
