# Generated by Django 2.0.1 on 2018-02-05 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0011_auto_20180205_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='matchedcat',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='matchedcat', to='cats.Cat', verbose_name='matched cat'),
        ),
        migrations.AlterField(
            model_name='match',
            name='matchingcat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matchingcat', to='cats.Cat', verbose_name="owner's cat"),
        ),
    ]
