# Generated by Django 2.0.1 on 2018-02-06 00:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0012_auto_20180205_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
