# Generated by Django 2.0.1 on 2018-02-06 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0013_auto_20180206_0007'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='seen',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cat',
            name='profilepic',
            field=models.URLField(blank=True, help_text='Optional. This will be scaled to a 1:1 aspect ratio.', null=True, verbose_name='profile picture'),
        ),
    ]
