# Generated by Django 2.0.1 on 2018-02-13 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0017_auto_20180212_0749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='pic1',
            field=models.ImageField(help_text='One picture required', upload_to='', verbose_name='picture 1'),
        ),
        migrations.AlterField(
            model_name='cat',
            name='pic2',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='picture 2'),
        ),
        migrations.AlterField(
            model_name='cat',
            name='pic3',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='picture 3'),
        ),
        migrations.AlterField(
            model_name='cat',
            name='profilepic',
            field=models.ImageField(blank=True, help_text='Optional. This will be clipped to a 1:1 aspect ratio.', null=True, upload_to='', verbose_name='profile picture'),
        ),
    ]
