# Generated by Django 2.0.1 on 2018-02-15 20:28

import cats.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0018_auto_20180213_0048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='pic1',
            field=models.ImageField(help_text='Picture 1 is required', upload_to=cats.models.cat_picture_path, verbose_name='picture 1'),
        ),
        migrations.AlterField(
            model_name='cat',
            name='pic2',
            field=models.ImageField(blank=True, null=True, upload_to=cats.models.cat_picture_path, verbose_name='picture 2'),
        ),
        migrations.AlterField(
            model_name='cat',
            name='pic3',
            field=models.ImageField(blank=True, null=True, upload_to=cats.models.cat_picture_path, verbose_name='picture 3'),
        ),
        migrations.AlterField(
            model_name='cat',
            name='profilepic',
            field=models.ImageField(blank=True, help_text='Optional. This will be clipped to a 1:1 aspect ratio.', null=True, upload_to=cats.models.cat_picture_path, verbose_name='profile picture'),
        ),
    ]
